version: "3.7"

services:

  netpalm-controller:
    build:
      context: .
      dockerfile: ./dockerfiles/netpalm_controller_dockerfile
    environment:
      - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
      - NETPALM_CONFIG=/code/config/config.json
      - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
    ports:
      - "9000:9000"
    networks:
      - "netpalm-network"
    depends_on:
      - redis
      - cisgo

  worker-pinned:
    image: netpalm_netpalm-controller
    command: python3 worker.py pinned
    environment:
      - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
      - NETPALM_CONFIG=/code/config/config.json
      - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
    depends_on:
      - redis
    networks:
      - "netpalm-network"

  worker-fifo:
    image: netpalm_netpalm-controller
    command: python3 worker.py fifo
    environment:
      - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
      - NETPALM_CONFIG=/code/config/config.json
      - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
    depends_on:
      - redis
    networks:
      - "netpalm-network"

  redis:
    build:
      context: .
      dockerfile: ./dockerfiles/netpalm_redis_dockerfile
    networks:
      - "netpalm-network"

  cisgo:
    build:
      context: ./dockerfiles
      dockerfile: cisgo_dockerfile
    networks:
      - "netpalm-network"

networks:

  netpalm-network:
    name: "netpalm-network"
