version: "3.7"

services:
  netpalm-controller:
    build:
      context: .
      dockerfile: ./dockerfiles/netpalm_controller_dockerfile
    environment:
      - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
      - NETPALM_CONFIG=/code/config/config.json
      - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
    ports:
      - "9000:9000"
    networks:
      - "netpalm-network"
    depends_on:
      - redis
      - cisgo

  worker-pinned:
    image: netpalm_netpalm-controller
    command: python3 worker.py pinned
    environment:
      - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
      - NETPALM_CONFIG=/code/config/config.json
      - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
    depends_on:
      - redis
    networks:
      - "netpalm-network"
  #    deploy:
  #      replicas: 2

  worker-fifo:
    image: netpalm_netpalm-controller
    command: python3 worker.py fifo
    environment:
      - NET_TEXTFSM=/usr/local/lib/python3.8/site-packages/ntc_templates/templates/
      - NETPALM_CONFIG=/code/config/config.json
      - NETPALM_LOG_CONFIG_FILENAME=/code/config/log-config.yml
    depends_on:
      - redis
    networks:
      - "netpalm-network"

  redis:
    build:
      context: .
      dockerfile: ./dockerfiles/netpalm_redis_dockerfile
    networks:
      - "netpalm-network"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - "netpalm-network"

  cisgo:
    image: apcela/cisshgo:v0.1.1
    ports:
      - "10005:10005" # one port just for convenience in case you need to ssh from outside for some reason
    networks:
      - "netpalm-network"

networks:
  netpalm-network:
    name: "netpalm-network"
